#based on:https://github.com/barrycommins/prometheus-eureka-spring-boot-demo/tree/master/prometheus-demo-app
global:
  scrape_interval: 15s
  scrape_timeout: 15s
  evaluation_interval: 15s
# scrape metrics from the prometheus server itself
scrape_configs:
  - job_name: prometheus
    scrape_interval: 15s
    scrape_timeout: 15s
    metrics_path: /metrics
    static_configs:
      - targets:
          - localhost:9090
  # Discover targets from Eureka and scrape metrics from them
  - job_name: eureka-discovery
    scrape_interval: 15s
    scrape_timeout: 15s
    eureka_sd_configs:
      - server: http://host.docker.internal:8761/eureka
        refresh_interval: 30s
    metrics_path: /actuator/prometheus
    relabel_configs:
      - source_labels: [__meta_eureka_app_instance_vip_address]
        target_label: application