spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: INVENTORY-MS
          uri: lb://INVENTORY-MS
          predicates:
            - Path=/api/inventory/**, /h2-console/inventory-ms/**
        - id: ORDER-MS
          uri: lb://ORDER-MS
          predicates:
            - Path=/api/order/**, /h2-console/order-ms/**
        - id: PAYMENT-MS
          uri: lb://PAYMENT-MS
          predicates:
            - Path=/api/payment/**