spring:
  application:
    name: order-ms
  config:
    import: configserver:http://localhost:8888/
server:
  port: 0

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
    metadata-map:
      metrics.path: /actuator/prometheus
      health.path: /actuator/health
      management.context-path: /actuator

management:
  metrics:
    tags:
      application=${spring.application.name}:
